version: '3.8'

services:
  app:
    container_name: ping-server
    #image: ping_server:v1
    build:
      context: ./../
      dockerfile: ./docker/ping-local.dockerfile
      args:
        ENV: local
    ports:
      - 3050:8080
    volumes:
      - "./../app/core:/app/code"
      - "./../../tmp:/app/tmp"
      - "./../../logs:/app/logs"
      - "./../docker/env/ping-local.env:/app/code/.env"
    networks:
      ping:
        ipv4_address: 172.2.0.3
    privileged: true

networks:
  ping:
    external: false
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.2.0.0/16
          gateway: 172.2.0.1